[package]
name = "iksemel-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
iksemel = { path = ".." }

[[bin]]
name = "xml"
path = "fuzz_targets/xml.rs"
test = false
doc = false
bench = false

[workspace]
members = ["."]
